protected/models/User.php
<?php

class User extends CActiveRecord
{
	
	/**
	 * The followings are the available columns in table 'tbl_user':
	 * @var integer $id
	 * @var string $username
	 * @var string $password
	 * @var string $email
	 * @var string $profile
	 */
const LEVEL_REGISTERED=0, LEVEL_CONTACTO = 10, LEVEL_COORDINADOR = 55, LEVEL_EJECUTIVO = 50, LEVEL_ADMIN=99,  LEVEL_ROOT=100, LEVEL_OPERADOR = 75;
 
 /**
  * define the label for each level
  * @param int $level the level to get the label or null to return a list of labels
  * @return array|string
  */


public function getaccess($lv)
{
    if($lv == 'Root') {
        return 100; 
    } elseif($switch == 'Administrador del sistema') {
        return 99; 
    }
     elseif($switch == 'Operador (Telefonista)') {
        return 75; 
    }
	 elseif($switch == 'Coordinador General') {
        return 55; 
    }
     elseif($switch == 'Ejecutivo') {
        return 50; 
    }
     elseif($switch == 'Contacto') {
        return 10; 
    }
     else {
        return 0; 
    }
}


 static function getAccessLevelList( $level = null ){
  	
	 $levelList=array(

	self::LEVEL_ROOT => 'Root',
	self::LEVEL_ADMIN => 'Administrador del sistema',
	self::LEVEL_OPERADOR => 'Operador (Telefonista)',
	self::LEVEL_COORDINADOR => 'Coordinador General',
	self::LEVEL_EJECUTIVO => 'Ejecutivo',
	self::LEVEL_CONTACTO => 'Contacto'
  );

  	if(!Yii::app()->user->getisRoot())
		unset($levelList[100]);
  	if(!Yii::app()->user->getisAdmin()){
		unset($levelList[99]);
			
	}
  	if(!Yii::app()->user->getisOperador()){
		unset($levelList[75]);
		unset($levelList[55]);
	}
	if(!Yii::app()->user->getisCoordgen())
		unset($levelList[55]);	
	if(!Yii::app()->user->getisEjecutivo())
		unset($levelList[50]);
	if(!Yii::app()->user->getisContacto())
		unset($levelList[10]);
	
  if( $level === null)
   return $levelList;
  return $levelList[ $level ];
 }
	/**
	 * Returns the static model of the specified AR class.
	 * @return CActiveRecord the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{user}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		$accs = 'user_id, firstname, lastname, username, password';

		return array(
			//array('image', 'file', 'types'=>'jpg, gif, png'),
			array($accs, 'required'),
				
			array('user_id, status, accessLevel', 'numerical', 'integerOnly'=>true),
			array('firstname, lastname, username, password,  email, direccion, salt', 'length', 'max'=>128),
			array('user_id, firstname, lastname, username, direccion, salt, email, id_empresa, date_added, status, accessLevel', 'safe'),


		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			//'posts' => array(self::HAS_MANY, 'Post', 'author_id'),
			'accessLevel' => array(self::BELONGS_TO, 'User', 'accessLevel'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			
			'user_id' => 'Id',
			'username' => 'Nombre de Usuario',
			'firstname' => 'Nombre(s)',
			'lastname' => 'Apellido(s)',
			'password' => 'Password',
			'date_added' => 'Fecha de ingreso',
			'id_empresa' => 'Empresa',
			'status' => 'Estado',
			'accessLevel' => 'Nivel de acceso',
			
		);
	}
public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('username',$this->username,true);
		
		$criteria->compare('email',$this->email,true);
		
		$criteria->compare('id_empresa',$this->id_empresa);
		
		$criteria->compare('date_added',$this->date_added,true);

		$criteria->compare('status',$this->status);
		
		
		if((!Yii::app()->user->getIsEjecutivo()) && (Yii::app()->user->getisContacto())){
			$criteria->compare('accessLevel', User::model()->findByPk(Yii::app()->user->id_user)->accessLevel);
		}

		if((Yii::app()->user->getIsEjecutivo()) && (!Yii::app()->user->getisCoordgen())){
			$criteria->compare('accessLevel  <', User::model()->findByPk(Yii::app()->user->id_user)->accessLevel);
		}		
		if((Yii::app()->user->getisCoordgen()) && (!Yii::app()->user->getisOperador())){
			$criteria->compare('accessLevel  <', User::model()->findByPk(Yii::app()->user->id_user)->accessLevel);
		}
		if((Yii::app()->user->getisOperador()) && (!Yii::app()->user->getisAdmin())){
			$criteria->compare('accessLevel  <', User::model()->findByPk(Yii::app()->user->id_user)->accessLevel);
		}
		
		if((!Yii::app()->user->getIsRoot()) && (Yii::app()->user->getisAdmin())){	
			$criteria->compare('accessLevel  <', User::model()->findByPk(Yii::app()->user->id_user)->accessLevel);
		}
		
		return new CActiveDataProvider(get_class($this),array(
    'pagination'=>array(
        'pageSize'=> Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']),
    ),
    'criteria'=>$criteria,
));
		//return new CActiveDataProvider('User', array(
		//	'criteria'=>$criteria,
		//));
	}
	/**
	 * Checks if the given password is correct.
	 * @param string the password to be validated
	 * @return boolean whether the password is valid
	 */
	
	
	
	public function validatePassword($password)
	{

		if($this->status == 1){
			if($this->password === sha1($this->salt.sha1($this->salt.sha1($password))))
				return true;
			if($this->password === md5($password))
				return true;
			else{
				echo md5($password);
				return false;
				}
			}
		else
			return false;
		//"password = SHA1(CONCAT(salt, SHA1(CONCAT(salt, SHA1('" . $this->db->escape($password) . "'))))) OR password = '" . $this->db->escape(md5($password)) . "') "
		//return CPasswordHelper::verifyPassword($password,$this->password);
	}

	/**
	 * Generates the password hash.
	 * @param string password
	 * @return string hash
	 */
	public function hashPassword($password)
	{
		return md5($password);
		//return CPasswordHelper::hashPassword($password);
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{

	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(

	array('allow',
		'actions'=>array('view','create','delete','update', 'admin', 'excel'),
		'expression'=>'$user->getisAdmin()',
    ),

	array('allow',
		'actions'=>array('importar', 'importarexcel'),
		'expression'=>'$user->getisOperador()',
    ),

	array('allow',
		'actions'=>array('create','delete','update', 'admin', 'excel'),
		'expression'=>'$user->getIsEjecutivo()',
    ),	
	array('allow',
		'actions'=>array('view','update', 'index'),
		'expression'=>'$user->getisContacto()',
		),
	
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionImportarexcel()
	{
		$this->render('importar_excel');
	}

	
	public function actionImportar()
	{
		$this->render('importar');
	}
	
	public function actionExcel()
	{
		$this->render('excel');
	}
	
	public function actionView()
	{

			$this->render('view',array(
				'model'=>$this->loadModel(),
			));
		
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{

		
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
		
			$model->password =  md5($model->password);
			
			if($model->save())
				$this->redirect(array('view','id'=>$model->user_id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();
		$passwd = $model->password;
		
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		
		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
		
			if($passwd != $model->password)
			$model->password = md5($model->password);
			
			
			if($model->save())
				$this->redirect(array('index'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
			if(!Yii::app()->user->getIsAdmin()) 
			throw new CHttpException(400,'Ud. no tiene los permisos para acceder.');
			else{

		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Respuesta Invalida.');
	}
	}
	/**
	 * Lists all models.
	 */
	

	public function actionIndex()
	{


		//$dataProvider=new CActiveDataProvider('User');
		$model=new User('search');
				$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];
		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		if (isset($_GET['pageSize'])) {
		Yii::app()->user->setState('pageSize',(int)$_GET['pageSize']);
		unset($_GET['pageSize']);  // would interfere with pager and repetitive page size change
		}

		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=User::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'La pagina no existe.');
		}
		return $this->_model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_form.php
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'upload-form',
	'enableAjaxValidation'=>false,
	 'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>

<div class="box box-primary box-header with-border">
<? if(!$model->isNewRecord){ ?>	
<h2 class="box-title">Administrar cliente</h2>
<?}
else{
?>
<h2 class="box-title">Registrar cliente</h2>
<?}?>

<div class="pull-right">
	<div class="row box-footer">
		<?echo CHtml::tag('button',
                array('class' => 'btn btn-large pull-right btn btn-primary', 'onclick'=> '"this.form.submit()"'),
                '<i class="fa fa-save"></i>');
                ?>
	</div>
</div>

</div>

<div class="box-body">

	<p class="note">Los campos con <span class="required">*</span> son necesarios.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="form-group">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>128, 'class' => 'form-control')); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>
	
	<div class="form-group">
		<?php echo $form->labelEx($model,'id_empresa'); ?>
		<?php echo $form->dropDownList($model,'id_empresa', CHtml::listData(cliente::model()->findAll(array('order'=>'razon_social')), 'customer_id','razon_social'), array('empty'=>'Seleccionar..', 'class' => 'form-control')); ?>
		<?php echo $form->error($model,'empresa'); ?>
	</div>
	
	<div class="form-group">
		<?php echo $form->labelEx($model,'firstname'); ?>
		<?php echo $form->textField($model,'firstname',array('size'=>60,'maxlength'=>128, 'class' => 'form-control')); ?>
		<?php echo $form->error($model,'firstname'); ?>
	</div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'lastname'); ?>
		<?php echo $form->textField($model,'lastname',array('size'=>60,'maxlength'=>128, 'class' => 'form-control')); ?>
		<?php echo $form->error($model,'lastname'); ?>
	</div>
	
	<div class="form-group">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>128, 'class' => 'form-control')); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>
	
	<div class="form-group">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password',array('size'=>60,'maxlength'=>128, 'class' => 'form-control')); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>
	
	<?
	if( Yii::app()->user->getIsAdmin()){
	?>
	<div class="form-group">
		<?php echo $form->labelEx($model,'accessLevel'); ?>
		<?php echo $form->dropDownList($model,'accessLevel',$model->getAccessLevelList(), array('class' => 'form-control')); ?>
		<?php echo $form->error($model,'accessLevel'); ?>
	</div>
	<?}?>
	
	<!--div class="form-group">
		< ?php echo CHtml::submitButton($model->isNewRecord ? 'Agregar' : 'Guardar'); ?>
	</div-->

<?php $this->endWidget(); ?>

</div><!-- form -->
<br><br>

protected/views/user/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<!--div class="row">
		< ?php echo $form->label($model,'id'); ?>
		< ?php echo $form->textField($model,'id'); ?>
	</div-->
	<table>
		<tr>
		<td>
	<div class="form-group">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="form-group">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>128)); ?>
	</div>
	</td>
	<td style="padding-left: 20px;">
	
	<div class="form-group">
		<?php echo $form->labelEx($model,'id_empresa'); ?>
		<?php echo $form->dropDownList($model,'id_empresa', CHtml::listData(cliente::model()->findAll(array('order'=>'razon_social')), 'customer_id','razon_social'), array('empty'=>'Seleccionar..', 'class' => 'form-control')); ?>
	</div>
		
	<div class="form-group">
		<?php echo $form->label($model,'date_added'); ?>
		<?php echo $form->dateField($model,'date_added',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="form-group">
		<?php echo CHtml::label('Activo','activo'); ?>
		<?php echo $form->checkBox($model,'status',array('size'=>60,'maxlength'=>128)); ?>
	</div>
		</td>
		</tr>
	</table>
	<div class="form-group">
		<?php echo CHtml::submitButton('Buscar', array('class' => 'btn btn-primary')); ?>
	</div>
	
<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/_view.php
<div class="view">
	
	<div>
	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CHtml::encode($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('programa')); ?>:</b> 
	<?php echo CHtml::encode(programa::model()->findByPk($data->programa)->programa_desc); ?>
	<br />
	</div>

</div>
<br><br>

protected/views/user/admin.php
<?php

$pageSize=Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']); ?>

<?php
// we use header of button column for the drop down
// so change the CButtonColumn in columns array like this:



$this->breadcrumbs=array(
	'Usuarios'=>array('index'),
	'Administrar',
);

	if(!Yii::app()->user->getisOperador() )
$this->menu=array(
	array('label'=>'Listar Usuario', 'url'=>array('index')),
	array('label'=>'Crear Usuario', 'url'=>array('create')),
);
else
$this->menu=array(
	array('label'=>'Listar Usuario', 'url'=>array('index')),
	array('label'=>'Crear Usuario', 'url'=>array('create')),
	array('label'=>'Importar Usuarios', 'url'=>array('importar')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#user-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Administrar Usuarios</h1>


<!--?php echo CHtml::link('Busqueda Avanzada','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
< ?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'username',
		'email',
		'direccion',
			array(
		'name' => 'programa',
            'value'=> 'programa::model()->findByPk($data->programa)->desc_programa',
		),
		array(
		'name' => 'accessLevel',
		'value' => '($data->accessLevel == 100) ? "Root" : (($data->accessLevel == 99) ? "Administrador" : (($data->accessLevel == 55) ? "Coordinador General" : (($data->accessLevel == 50) ? "Ejecutivo" : "Contacto" )))',
		),
		
		array(
    'class'=>'CButtonColumn',
    'header'=>CHtml::dropDownList('pageSize',$pageSize,array(20=>20,50=>50,100=>100),array(
        // change 'user-grid' to the actual id of your grid!!
        'onchange'=>"$.fn.yiiGridView.update('user-grid',{ data:{pageSize: $(this).val() }})",
    )),
),
		//array(
		//	'class'=>'CButtonColumn',
		//),
	),
)); ?>
<br><br>

protected/views/user/create.php
<?php
$this->breadcrumbs=array(
	'Usuarios'=>array('index'),
	'Crear',
);

$this->menu=array(
	array('label'=>'Crear Usuario', 'url'=>array('create')),
	array('label'=>'Administrar Usuarios', 'url'=>array('admin')),
);
?>

<h1>Registrar Usuario</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/user/excel.php
<?php
function autosize($objPHPExcel){
	for($col = 'A'; $col !== 'Z'; $col++) {
    $objPHPExcel->getActiveSheet()
       ->getColumnDimension($col)
        ->setAutoSize(true);
	}
}

$this->layout=false;	
	Yii::import('application.extensions.phpexcel.PHPExcel');
	
	$objPHPExcel = new PHPExcel();
	$objPHPExcel->getProperties()->setCreator("cityexpress")
    ->setLastModifiedBy("cityexpress");	
	
	$objPHPExcel->setActiveSheetIndex(0);
	$objPHPExcel->getActiveSheet()->setTitle('Usuarios');
	autosize($objPHPExcel);
	//$j++;
	
			$formato_header = array(
				'fill' => array(
				'type' => PHPExcel_Style_Fill::FILL_SOLID,
				'color' => array('rgb' => '00B0F0')
				),
				'font'  => array(
				'bold'  => true,
				'color' => array('rgb' => 'FFFFFF')
				),

				);

			$formato_bordes = array(
					'borders' => array(
			'allborders' => array(
			'style' => PHPExcel_Style_Border::BORDER_THIN,
			),
			));

			
		
			$objPHPExcel->getActiveSheet()->getStyle('A1:D1')->applyFromArray($formato_header);
			$objPHPExcel->getActiveSheet()->getStyle('A1:D1')->applyFromArray($formato_bordes);

			
			$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, 1, 'ID_USER');
			$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, 1, 'NOMBRE');
			$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, 1, 'EMAIL');
			$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, 1, 'CARGO');
				
				
				$sql ='';
				
				
				if( User::model()->findByPk(Yii::app()->user->id)->accessLevel == 99){
					$sql .=' where accessLevel <= '.User::model()->findByPk(Yii::app()->user->id)->accessLevel;
				}

				if( User::model()->findByPk(Yii::app()->user->id)->accessLevel == 75){
					$sql .=' where accessLevel <= '.User::model()->findByPk(Yii::app()->user->id)->accessLevel;
				}				
				
				if( User::model()->findByPk(Yii::app()->user->id)->accessLevel <= 50){
					$sql .=' where programa = '.User::model()->findByPk(Yii::app()->user->id)->programa;
				}
				
				$proveedores = Yii::app()->db->createCommand('SELECT * FROM tbl_user'.$sql)->queryAll();
				
				$i=0;
				foreach($proveedores as $p){
				
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(0, ($i+2), $p['id']);
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(1, ($i+2), $p['username']);
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(2, ($i+2), $p['email']);
				
				if( $p['accessLevel'] == 10)
					$ac = 'Contacto';
				if( $p['accessLevel'] == 100)
					$ac = 'Root';
				if( $p['accessLevel'] == 99)
					$ac = 'Administrador';
				if( $p['accessLevel'] == 75)
					$ac = 'Telefonista';
				if( $p['accessLevel'] == 50)
					$ac = 'Ejecutivo';
				
				$objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow(3, ($i+2), $ac);
				
				$i++;
				}
	

	


    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="usuarios.xls"');
    header('Cache-Control: max-age=0');
    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
    $objWriter->save('php://output');

?>

protected/views/user/index.php
<?php
function get_empresa($id_empresa){
	$co = Yii::app()->db->createCommand('Select count(*) from assert_customer where customer_id = '.$id_empresa)->queryScalar();
	if($co == 0)
		return '---';
	else
		return cliente::model()->findByPk($id_empresa)->razon_social;
	}

function parsedate($fecha){
	return date('d-m-Y', strtotime($fecha));
	}

	
$this->breadcrumbs=array(
	'Usuarios',
);

?>

<div class="box box-primary box-header with-border">
<h2 class="box-title">Administrar Usuarios</h2>
<div class="pull-right">
<a href="<? echo Yii::app()->createUrl("user/create"); ?>" class="btn btn-primary"><i class="fa fa-plus"></i></a>
<a href="<? echo Yii::app()->createUrl("user/excel"); ?>" class="btn btn-success"><i class="fa fa-file-excel-o"></i></a>
</div>
</div>

<div class="search-form">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'columns'=>array(
		//'id',
		'username',
		'email',
		array(
		'name' => 'id_empresa',
		'value' => 'get_empresa($data->id_empresa)',
		),

		array(
		'name' => 'date_added',
		'value' => 'parsedate($data->date_added)',
		),

		array(
		'name' => 'status',
		'value' => '($data->status == 1) ? "Activo" : "Inactivo"',
		),
		
		
		array(
		'name' => 'accessLevel',
		'value' => '($data->accessLevel == 100) ? "Root" : (($data->accessLevel == 99) ? "Administrador" : (($data->accessLevel == 55) ? "Coordinador General" : (($data->accessLevel == 50) ? "Ejecutivo" : "Contacto" )))',
		),
				
		array(
			'class'=>'CButtonColumn',
			'template' => '{editar} {borrar}',
    		'htmlOptions' => array('style' => 'width: 170px;'),
    		 'buttons'=>array
				(
				'editar' => array
				(
					'label'=>'<button class="btn btn-primary"><i class="fa fa-pencil"></i></button>',
					 'options'=>array('title'=>''),
					 'url'=>'Yii::app()->createUrl("user/update", array("id"=>$data->user_id))',
						
				),	
				'borrar' => array
				(
					'label'=>'<button class="btn btn-danger"><i class="fa fa-trash"></i></button>',
					'options'=>array('title'=>''),
					'url'=>'Yii::app()->createUrl("user/delete", array("id"=>$data->user_id))',
					
				),
				),
    ),
	),
)); ?>
<br><br>